source "/Users/tsukimizake/Library/Application Support/nushell/plugins/yarn-completion.nu"
source "/Users/tsukimizake/Library/Application Support/nushell/plugins/man-completions.nu"
source "/Users/tsukimizake/Library/Application Support/nushell/plugins/make-completions.nu"
source "/Users/tsukimizake/Library/Application Support/nushell/plugins/just-completions.nu"
source "/Users/tsukimizake/Library/Application Support/nushell/plugins/cargo-completions.nu"
source "/Users/tsukimizake/Library/Application Support/nushell/plugins/npm-completions.nu"
source "/Users/tsukimizake/Library/Application Support/nushell/plugins/rustup-completions.nu"
source "/Users/tsukimizake/Library/Application Support/nushell/plugins/mysql-completions.nu"
source "/Users/tsukimizake/Library/Application Support/nushell/plugins/mix-completions.nu"
source "/Users/tsukimizake/Library/Application Support/nushell/plugins/zellij-completions.nu"
source "/Users/tsukimizake/workdir/nushell-config/plugins/git-completions.nu"
